language: generic
sudo: required

services:
    - docker

before_install:
    - docker build -t anbalgantamilarasan/createreactapp-docker -f Dockerfile.dev .

script:
    - docker run -e CI=true anbalgantamilarasan/createreactapp-docker npm run test